# Generated by Django 2.2.7 on 2019-11-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('contact_name', models.EmailField(max_length=254)),
                ('contact_gst_number', models.CharField(max_length=20)),
            ],
        ),
    ]
